# Generated by Django 5.0.6 on 2024-07-04 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=14, null=True, verbose_name='CPF')),
                ('telefone', models.CharField(max_length=16, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('endereco', models.CharField(max_length=150, verbose_name='endereço')),
            ],
        ),
        migrations.CreateModel(
            name='Filtro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
                ('descricao', models.CharField(max_length=70, verbose_name='descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Oleo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
                ('descricao', models.CharField(max_length=70, verbose_name='descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=8)),
                ('cor', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=50)),
                ('ano', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modulos.cliente')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modulos.marca')),
            ],
        ),
    ]
