# Generated by Django 5.0.6 on 2024-10-04 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Troca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('kmpt', models.IntegerField()),
                ('filtro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulos.filtro')),
                ('oleo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulos.oleo')),
                ('placa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulos.veiculo')),
            ],
        ),
    ]
